export 'package:primer_proyecto/screens/slider_screen.dart';
export 'package:primer_proyecto/screens/inputs_screen.dart';
export 'package:primer_proyecto/screens/animated_screen.dart';
export 'package:primer_proyecto/screens/avatar_screen.dart';
export 'package:primer_proyecto/screens/alert_screen.dart';
export 'package:primer_proyecto/screens/card_screen.dart';
export 'package:primer_proyecto/screens/home_screen.dart';
export 'package:primer_proyecto/screens/listview_screen.dart';
export 'package:primer_proyecto/screens/listview2_screen.dart';
